name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required to checkout and push to the repo

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Git Identity
      - name: Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: |
          cd lib
          bun run build

      # Bump Versions (reinstate after release)
      - name: Bump versions
        run: |
          cd lib
          bun version

      # Pull latest changes and rebase before pushing
      - name: Pull and Push changes
        run: |
          git pull --rebase origin main
          git push --follow-tags origin main

      # Create Release
      - name: Publish
        run: |
          cd lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
