name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependencies
      - run: bun install --frozen-lockfile && cd lib

      # Git Identity
      - name: Git Identity
        run: |
          git config --global user.name 'CI-CD'
          git config --global user.email 'CI-CD@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Bump Versions (reinstate after release)
      - name: Bump versions
        run: bun version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create Release
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
